name: build_Release

on:
  push:
    branches:
      - 113
  workflow_dispatch:

env:
  VERSION: '1.1.3'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bootstrap Procursus
        uses: w2599/procursus-action@main
        with:
          packages: ldid trustcache make findutils coreutils
          cache: true
          cache-path: ~/__cache
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos

      - name: Pre env
        run: |
         sT=$(TZ=UTC-8 date +'%S')
         echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
         echo "shT=$(TZ=UTC-8 date +'%Y.%m.%d/%H.%M').${sT}" >> $GITHUB_ENV
         echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Log env
        run: |
         echo ${{ env.VERSION }}
         echo ${{ env.msT }}
         echo ${{ env.shT }}
         echo ${{ env.logT }}

      - name: Pre code
        run: |
          sed -i '' "s/AAA/ /g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAB/编译于${{ env.logT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAC/${{ env.msT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/CCC/${{ secrets.DOPAMINE_TOKEN }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/CCC/${{ secrets.DOPAMINE_TOKEN }}/g" ./Dopamine/Dopamine/UI/Views/UpdateDownloadingView.swift
          sed -i '' "s/"opa334"/"w2599"/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/opa334/w2599/g" ./Dopamine/Dopamine/UI/Views/UpdateDownloadingView.swift
          sed -i '' 's/MARKETING_VERSION = .*;/MARKETING_VERSION = ${{ env.VERSION }};/g' ./Dopamine/Dopamine.xcodeproj/project.pbxproj

      - name: Pre body
        run: |
          echo -e "版本：${{ env.VERSION }} (尝鲜版)\n编译时间戳：${{ env.msT }}\n北京时间：${{ env.shT }}" >> body.txt
          echo -e "\n增删改：" >> body.txt
          echo -e "${{ env.logT }}" >> body.txt
          echo -e "> - 同步master代码" >> body.txt
          # echo -e "> - 新增开机时长显示" >> body.txt
          # echo -e "> - 尝试修一下ota代码" >> body.txt

      - name: Pre keychain
        run: |
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A

      - name: Build tipa
        run: |
          set -x
          export THEOS=$HOME/theos
          gmake -j$(sysctl -n hw.physicalcpu)
          cp Dopamine/Dopamine.tipa Dopamine.tipa
          mv Dopamine/Dopamine.tipa Dopamine_${{ env.msT }}.tipa

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: 113
          body_path: body.txt
          prerelease: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.tipa

      - name: Upload Latest Artifact
        id: dopamine-latest-upload
        uses: actions/upload-artifact@v3
        with:
          name: Dopamine_Latest
          path: |
            Dopamine.tipa
